var name="Darshan", school="NES High", grade="10th", section="B", rollno="36";
console.log("Name    : ", name);
console.log("School  : ", school);
console.log("Grade   : ", grade);
console.log("Section : ", section);
console.log("Roll No.: ", rollno);
var subject, marks;
console.log("***************************");
console.log("*   Subject   *   Marks   *");
subject="Maths";
marks = 95;
console.log("*  ", subject, "    *  ", marks, "     *");
subject = "Science";
marks = 85;
console.log("*  ", subject, "  *  ", marks, "     *");
subject = "English";
marks = 91;
console.log("*  ", subject, "  *  ", marks, "     *");
console.log("***************************");